services:
  # --- THE DATABASE ---
  db:
    image: postgres:latest
    container_name: eap-postgres-container
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      # Format is "Host_Port:Container_Port"
      # This allows your laptop to connect via VPS_IP:5431
      - "5431:5432"
    networks:
      - eap-network

  # --- THE BACKEND ---
  backend:
    image: yuvalmotopp/backend_fastapi:latest
    container_name: eap-backend-container
    env_file:
      - ./.env
    volumes:
      # VPS Folder : Container Path
      - ./user_images:/app/images
    depends_on:
      - db
    networks:
      - eap-network

  # --- THE FRONTEND ---
  frontend:
    container_name: eap-frontend-container
    image: yuvalmotopp/eap-frontend:latest
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Map the same VPS folder to Nginx's web root
      - ./user_images:/usr/share/nginx/html/images:ro
    depends_on:
      - backend
    networks:
      - eap-network

volumes:
  pgdata:

networks:
  eap-network:
    driver: bridge